package com.example.backend.entity;

public enum AuditAction {
    CREATED,
    DELETED,
    STATUS_CHANGED,
    PRIORITY_CHANGED,
    TITLE_CHANGED,
    DESCRIPTION_CHANGED,
    CATEGORY_CHANGED,
    DUE_DATE_CHANGED,
    ASSIGNEE_ADDED,
    ASSIGNEE_REMOVED,
    GITHUB_PUSH,
    GITHUB_PR_OPENED,
    GITHUB_PR_MERGED,
    GITHUB_PR_CLOSED
}